import { useEffect, useState } from "react"
import "./App.css"

http://127.0.0.1:80const API_URL = "https://risk-based-access-intelligence-engine.onrender.com"01

function App() {
  const [form, setForm] = useState({
    user_id: "Alice",
    device_trusted: true,
    device_secure: true,
    location_known: true,
    behaviour_anomaly: 10,
    access_frequency: 10,
    resource_sensitivity: 20,
    failed_attempts: 0,
    threat_level: "none",
  })

  const [result, setResult] = useState(null)
  const [mlResult, setMlResult] = useState(null)
  const [threatIntel, setThreatIntel] = useState(null)
  const [history, setHistory] = useState([])
  const [loading, setLoading] = useState(false)
  const [status, setStatus] = useState(
    "Ready to evaluate access"
  )

  function updateField(name, value) {
    setForm((previous) => ({
      ...previous,
      [name]: value,
    }))
  }

  async function loadHistory() {
    try {
      const response = await fetch(
        `${API_URL}/access/history`
      )

      if (!response.ok) {
        throw new Error("History API error")
      }

      const data = await response.json()

      setHistory(data.history || [])
    } catch (error) {
      console.log(
        "Unable to load access history",
        error
      )
    }
  }

  useEffect(() => {
    loadHistory()

    const interval = setInterval(() => {
      loadHistory()
    }, 5000)

    return () => clearInterval(interval)
  }, [])

  async function evaluateAccess() {
    setLoading(true)

    setStatus(
      "Evaluating risk, ML behaviour and threat intelligence..."
    )

    try {
      const response = await fetch(
        `${API_URL}/access/evaluate`,
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify(form),
        }
      )

      if (!response.ok) {
        throw new Error("Backend error")
      }

      const data = await response.json()

      setResult(data.access_evaluation)

      setMlResult(data.ml_behaviour)

      setThreatIntel(data.threat_intelligence)

      await loadHistory()

      setStatus(
        "Decision generated by FastAPI + ML + Threat Intelligence"
      )
    } catch (error) {
      console.error(error)

      setStatus(
        "Backend unavailable — please check FastAPI"
      )

      setResult(null)
      setMlResult(null)
      setThreatIntel(null)
    } finally {
      setLoading(false)
    }
  }


  // =====================================================
  // DASHBOARD STATISTICS
  // =====================================================

  const totalRequests = history.length

  const allowCount = history.filter(
    (item) => item.decision === "ALLOW"
  ).length

  const challengeCount = history.filter(
    (item) => item.decision === "CHALLENGE"
  ).length

  const restrictCount = history.filter(
    (item) => item.decision === "RESTRICT"
  ).length

  const denyCount = history.filter(
    (item) => item.decision === "DENY"
  ).length

  const averageRisk =
    history.length > 0
      ? Math.round(
          history.reduce(
            (sum, item) =>
              sum + Number(item.risk_score || 0),
            0
          ) / history.length
        )
      : 0

  const latestMLAnomaly =
    history.length > 0
      ? history[0].ml_anomaly_score ?? 0
      : mlResult?.anomaly_score ?? 0

  const latestThreatScore =
    history.length > 0
      ? history[0].threat_score ?? 0
      : threatIntel?.threat_score ?? 0

  const latestThreatLevel =
    history.length > 0
      ? history[0].intelligence_threat_level || "NONE"
      : threatIntel?.threat_level || "NONE"

  const decisionClass =
    result?.decision?.toLowerCase() || ""

  const mlStatusClass =
    mlResult?.status?.toLowerCase() || ""

  const threatLevelClass =
    threatIntel?.threat_level?.toLowerCase() || ""


  return (
    <div className="app">

      {/* =================================================
          HEADER
      ================================================= */}

      <header className="header">

        <div>
          <h1>
            🛡️ Risk-Based Access Intelligence Engine
          </h1>

          <p>
            Context-Aware • Risk-Sensitive • Continuous Access Evaluation
          </p>
        </div>

        <div className="monitor-badge">
          <span className="monitor-dot"></span>
          Monitoring Active
        </div>

      </header>


      <main className="container">

        {/* =================================================
            OVERVIEW
        ================================================= */}

        <section className="overview-grid">

          <div className="stat-card">
            <span className="stat-icon">
              📊
            </span>

            <div>
              <span className="stat-label">
                Total Requests
              </span>

              <strong>
                {totalRequests}
              </strong>
            </div>
          </div>


          <div className="stat-card">
            <span className="stat-icon allow-icon">
              ✓
            </span>

            <div>
              <span className="stat-label">
                Allowed
              </span>

              <strong>
                {allowCount}
              </strong>
            </div>
          </div>


          <div className="stat-card">
            <span className="stat-icon challenge-icon">
              !
            </span>

            <div>
              <span className="stat-label">
                Challenged
              </span>

              <strong>
                {challengeCount}
              </strong>
            </div>
          </div>


          <div className="stat-card">
            <span className="stat-icon restrict-icon">
              ◐
            </span>

            <div>
              <span className="stat-label">
                Restricted
              </span>

              <strong>
                {restrictCount}
              </strong>
            </div>
          </div>


          <div className="stat-card">
            <span className="stat-icon deny-icon">
              ×
            </span>

            <div>
              <span className="stat-label">
                Denied
              </span>

              <strong>
                {denyCount}
              </strong>
            </div>
          </div>


          <div className="stat-card">
            <span className="stat-icon">
              ⚖
            </span>

            <div>
              <span className="stat-label">
                Average Risk
              </span>

              <strong>
                {averageRisk}
              </strong>
            </div>
          </div>

        </section>


        {/* =================================================
            LIVE MONITORING
        ================================================= */}

        <section className="monitor-card">

          <div className="monitor-header">

            <div>
              <h2>
                🔎 Live Risk Monitoring
              </h2>

              <p>
                Continuous access activity and intelligence monitoring
              </p>
            </div>

            <div className="refresh-label">
              Auto refresh: 5s
            </div>

          </div>


          <div className="monitor-grid">

            <div className="monitor-item">
              <span>
                Latest ML Anomaly
              </span>

              <strong>
                {latestMLAnomaly}
              </strong>
            </div>


            <div className="monitor-item">
              <span>
                Latest Threat
              </span>

              <strong
                className={
                  latestThreatLevel.toLowerCase()
                }
              >
                {latestThreatLevel}
              </strong>
            </div>


            <div className="monitor-item">
              <span>
                Latest Decision
              </span>

              <strong
                className={
                  history[0]?.decision
                    ? history[0].decision.toLowerCase()
                    : ""
                }
              >
                {history[0]?.decision || "—"}
              </strong>
            </div>


            <div className="monitor-item">
              <span>
                Latest Risk
              </span>

              <strong>
                {history[0]?.risk_score ?? "—"}
              </strong>
            </div>

          </div>

        </section>


        {/* =================================================
            REQUEST + RESULT
        ================================================= */}

        <div className="grid">

          {/* =================================================
              ACCESS REQUEST
          ================================================= */}

          <section className="card">

            <div className="section-title">

              <div>
                <h2>
                  Access Request Context
                </h2>

                <p>
                  Configure the security context for the request
                </p>
              </div>

            </div>


            <div className="field">

              <label>
                User Identity
              </label>

              <input
                value={form.user_id}
                onChange={(e) =>
                  updateField(
                    "user_id",
                    e.target.value
                  )
                }
                placeholder="Enter user ID"
              />

            </div>


            <div className="field">

              <label>
                Device Trust
              </label>

              <select
                value={form.device_trusted}
                onChange={(e) =>
                  updateField(
                    "device_trusted",
                    e.target.value === "true"
                  )
                }
              >

                <option value="true">
                  Trusted Device
                </option>

                <option value="false">
                  Unknown Device
                </option>

              </select>

            </div>


            <div className="field">

              <label>
                Device Security
              </label>

              <select
                value={form.device_secure}
                onChange={(e) =>
                  updateField(
                    "device_secure",
                    e.target.value === "true"
                  )
                }
              >

                <option value="true">
                  Secure
                </option>

                <option value="false">
                  Security Issue
                </option>

              </select>

            </div>


            <div className="field">

              <label>
                Location
              </label>

              <select
                value={form.location_known}
                onChange={(e) =>
                  updateField(
                    "location_known",
                    e.target.value === "true"
                  )
                }
              >

                <option value="true">
                  Known Location
                </option>

                <option value="false">
                  Unusual Location
                </option>

              </select>

            </div>


            <div className="field">

              <label>

                Behaviour Anomaly

                <span className="range-value">
                  {form.behaviour_anomaly}
                </span>

              </label>

              <input
                type="range"
                min="0"
                max="100"
                value={form.behaviour_anomaly}
                onChange={(e) =>
                  updateField(
                    "behaviour_anomaly",
                    Number(e.target.value)
                  )
                }
              />

            </div>


            <div className="field">

              <label>

                Access Frequency

                <span className="range-value">
                  {form.access_frequency}
                </span>

              </label>

              <input
                type="range"
                min="0"
                max="100"
                value={form.access_frequency}
                onChange={(e) =>
                  updateField(
                    "access_frequency",
                    Number(e.target.value)
                  )
                }
              />

            </div>


            <div className="field">

              <label>

                Resource Sensitivity

                <span className="range-value">
                  {form.resource_sensitivity}
                </span>

              </label>

              <input
                type="range"
                min="0"
                max="100"
                value={form.resource_sensitivity}
                onChange={(e) =>
                  updateField(
                    "resource_sensitivity",
                    Number(e.target.value)
                  )
                }
              />

            </div>


            <div className="field">

              <label>
                Failed Access Attempts
              </label>

              <input
                type="number"
                min="0"
                value={form.failed_attempts}
                onChange={(e) =>
                  updateField(
                    "failed_attempts",
                    Number(e.target.value)
                  )
                }
              />

            </div>


            <div className="field">

              <label>
                Threat Signal
              </label>

              <select
                value={form.threat_level}
                onChange={(e) =>
                  updateField(
                    "threat_level",
                    e.target.value
                  )
                }
              >

                <option value="none">
                  None
                </option>

                <option value="low">
                  Low
                </option>

                <option value="medium">
                  Medium
                </option>

                <option value="high">
                  High
                </option>

                <option value="critical">
                  Critical
                </option>

              </select>

            </div>


            <button
              className="button"
              onClick={evaluateAccess}
              disabled={loading}
            >
              {loading
                ? "Evaluating Risk..."
                : "Evaluate Access"}
            </button>

          </section>


          {/* =================================================
              ACCESS INTELLIGENCE
          ================================================= */}

          <section className="card">

            <div className="section-title">

              <div>
                <h2>
                  Access Intelligence
                </h2>

                <p>
                  AI-assisted contextual access decision
                </p>
              </div>

            </div>


            {!result ? (

              <div className="empty-result">

                <div className="shield-icon">
                  🛡️
                </div>

                <h3>
                  Waiting for Access Request
                </h3>

                <p>
                  Configure the request context
                  and click Evaluate Access.
                </p>

              </div>

            ) : (

              <div className="result">

                {/* =================================================
                    RISK SCORE
                ================================================= */}

                <div className="risk-label">
                  Calculated Risk Score
                </div>

                <div className="score">
                  {result.risk_score}
                </div>

                <div
                  className={`decision ${decisionClass}`}
                >
                  {result.decision}
                </div>

                <p className="action-text">
                  {result.action}
                </p>


                {/* =================================================
                    ML ANALYSIS
                ================================================= */}

                {mlResult && (

                  <div className="ml-card">

                    <h3>
                      🤖 ML Behaviour Analysis
                    </h3>

                    <div className="ml-grid">

                      <div className="ml-box">

                        <span>
                          ML Anomaly Score
                        </span>

                        <strong>
                          {mlResult.anomaly_score}
                        </strong>

                      </div>


                      <div className="ml-box">

                        <span>
                          Behaviour Status
                        </span>

                        <strong
                          className={mlStatusClass}
                        >
                          {mlResult.status}
                        </strong>

                      </div>

                    </div>


                    <div className="ml-meta">

                      <div>
                        Model:
                        {" "}
                        {mlResult.model_status}
                      </div>

                      <div>
                        Prediction:
                        {" "}
                        {mlResult.prediction === 1
                          ? "Anomalous"
                          : "Normal"}
                      </div>

                    </div>

                  </div>

                )}


                {/* =================================================
                    THREAT INTELLIGENCE
                ================================================= */}

                {threatIntel && (

                  <div
                    className="ml-card"
                    style={{
                      marginTop: "16px",
                    }}
                  >

                    <h3>
                      🚨 Threat Intelligence
                    </h3>


                    <div className="ml-grid">

                      <div className="ml-box">

                        <span>
                          Threat Score
                        </span>

                        <strong>
                          {threatIntel.threat_score}
                        </strong>

                      </div>


                      <div className="ml-box">

                        <span>
                          Threat Level
                        </span>

                        <strong
                          className={
                            threatLevelClass
                          }
                        >
                          {threatIntel.threat_level}
                        </strong>

                      </div>

                    </div>


                    <div className="ml-meta">

                      <div>
                        Status:
                        {" "}
                        {threatIntel.status}
                      </div>

                      <div>
                        Indicators:
                        {" "}
                        {threatIntel.indicator_count}
                      </div>

                      <div>
                        Source:
                        {" "}
                        {threatIntel.source}
                      </div>

                    </div>


                    {threatIntel.indicators?.length > 0 && (

                      <div
                        style={{
                          marginTop: "12px",
                        }}
                      >

                        {threatIntel.indicators.map(
                          (indicator, index) => (

                            <div
                              className="reason"
                              key={index}
                            >
                              • {indicator}
                            </div>

                          )
                        )}

                      </div>

                    )}

                  </div>

                )}


                {/* =================================================
                    RISK FACTORS
                ================================================= */}

                <div className="risk-factors">

                  <h3>
                    Risk Factors
                  </h3>

                  {result.reasons?.map(
                    (reason, index) => (

                      <div
                        className="reason"
                        key={index}
                      >
                        • {reason}
                      </div>

                    )
                  )}

                </div>

              </div>

            )}


            <div className="status">
              {status}
            </div>

          </section>

        </div>


        {/* =================================================
            ACCESS HISTORY
        ================================================= */}

        <section className="card history-section">

          <div className="section-title history-title">

            <div>

              <h2>
                📊 Access History
              </h2>

              <p>
                Recent access activity monitored by the engine
              </p>

            </div>

            <span className="live-tag">
              ● LIVE
            </span>

          </div>


          {history.length === 0 ? (

            <p className="empty-history">
              No access history available yet.
            </p>

          ) : (

            <div className="history-table-wrapper">

              <table className="history-table">

                <thead>

                  <tr>

                    <th>
                      User
                    </th>

                    <th>
                      Time
                    </th>

                    <th>
                      Risk
                    </th>

                    <th>
                      Decision
                    </th>

                    <th>
                      Threat
                    </th>

                    <th>
                      Threat Score
                    </th>

                    <th>
                      Behaviour
                    </th>

                    <th>
                      ML Anomaly
                    </th>

                    <th>
                      Failed Attempts
                    </th>

                  </tr>

                </thead>


                <tbody>

                  {history.map(
                    (item, index) => (

                      <tr key={index}>

                        <td>
                          {item.user_id}
                        </td>

                        <td>
                          {item.timestamp}
                        </td>

                        <td>
                          <strong>
                            {item.risk_score}
                          </strong>
                        </td>

                        <td>

                          <span
                            className={`table-decision ${
                              item.decision?.toLowerCase() || ""
                            }`}
                          >
                            {item.decision}
                          </span>

                        </td>

                        <td>
                          {
                            item.intelligence_threat_level
                              || item.threat_level
                              || "-"
                          }
                        </td>

                        <td>
                          {item.threat_score ?? "-"}
                        </td>

                        <td>
                          {item.behaviour_anomaly}
                        </td>

                        <td>
                          {item.ml_anomaly_score ?? "-"}
                        </td>

                        <td>
                          {item.failed_attempts}
                        </td>

                      </tr>

                    )
                  )}

                </tbody>

              </table>

            </div>

          )}

        </section>


        {/* =================================================
            ENGINE PIPELINE
        ================================================= */}

        <section className="card pipeline-section">

          <div className="section-title">

            <div>

              <h2>
                ⚙️ How the Engine Works
              </h2>

              <p>
                Context → ML → Threat Intelligence → Risk → Decision
              </p>

            </div>

          </div>


          <div className="pipeline">

            <div className="pipeline-step">

              <span>
                👤
              </span>

              <strong>
                Identity
              </strong>

            </div>


            <div className="pipeline-arrow">
              →
            </div>


            <div className="pipeline-step">

              <span>
                💻
              </span>

              <strong>
                Device
              </strong>

            </div>


            <div className="pipeline-arrow">
              →
            </div>


            <div className="pipeline-step">

              <span>
                📍
              </span>

              <strong>
                Location
              </strong>

            </div>


            <div className="pipeline-arrow">
              →
            </div>


            <div className="pipeline-step">

              <span>
                🤖
              </span>

              <strong>
                ML Behaviour
              </strong>

            </div>


            <div className="pipeline-arrow">
              →
            </div>


            <div className="pipeline-step">

              <span>
                🚨
              </span>

              <strong>
                Threat Intel
              </strong>

            </div>


            <div className="pipeline-arrow">
              →
            </div>


            <div className="pipeline-step">

              <span>
                📊
              </span>

              <strong>
                Risk Engine
              </strong>

            </div>


            <div className="pipeline-arrow">
              →
            </div>


            <div className="pipeline-step">

              <span>
                ⚖️
              </span>

              <strong>
                Decision
              </strong>

            </div>

          </div>

        </section>

      </main>


      {/* =================================================
          FOOTER
      ================================================= */}

      <footer className="footer">

        Risk-Based Access Intelligence Engine

        <br />

        React + FastAPI + Python Risk Engine + ML + Threat Intelligence

      </footer>

    </div>
  )
}

export default App